3. Read file in binary mode and print first 40-50 characters. Note 40-50 is range, so it will start from 40th character to 50th.

File.read("d:output.txt")
=> "\"this is my file handling work is The canonical way to create a file object is by using the open() function. ... 
characters starting from the current reading position up to a newline character. ...
The readline() method will return the first line, and then will point to the second line in the file. ... 
Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object
is by using the open() function. ... characters starting from the current reading position up to a newline character.
... The readline() method will return the first line, and then will point to the second line in the file. ... 
Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a fil
e object is by using the open() function. ... characters starting from the current reading position up to a newline
character. ... The readline() method will return the first line, and then will point to the second line in the file.
... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to crea
te a file object is by using the open() function. ... characters starting from the current reading position up
to a newline character. ... The readline() method will return the first line, and then will point to the second 
line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical
way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function
. ... characters starting from the current reading position up to a newline character. ...
The readline() method will return the first line, and then will point to the second line in the file. ... 
Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object 
s by using the open() function. ... characters starting from the current reading position up to a newline character. ...
The readline() method will return the first line, and then will point to the second line in the file. ...
Use the 'rb' mode in the open() function to read a binary files, as shown ...
The canonical way to create a file object is by using the open() function. ... 
characters starting from the current reading position up to a newline character. ... 
The readline() method will return the first line, and then will point to the second line in the file. ...
Use the 'rb' mode in the open() function to read a binary files, as shown ...
The canonical way to create a file object is by using the open() function. ... c
haracters starting from the current reading position up to a newline character. ... The readline() method will return 
the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read
a binary files, as shown ...The canonical way to create a file object is by using the open() function. ...
characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ...
Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file.
... Use the 'rb' mode in the open() function to read a binary files, as shown ...\"\n"


real 0.59
user 0.43
sys 0.15
