10.List the files in the directory.Hint(Dir, FileUtils)

 Dir.glob("*/*.txt") do |my_text_file|
irb(main):116:1*   puts "working on: #{my_text_file}..."
irb(main):117:0> end
working on: todo_api_app/d:print.txt...
=> nil
irb(main):118:0> 

 Dir.glob("*/*.md") do |my_text_file|
irb(main):119:1*   puts "working on: #{my_text_file}..."
irb(main):120:0> end
working on: apidemofech/README.md...
working on: simpleapp/README.md...
working on: api_demo_application/README.md...
working on: Albumapplication/README.md...
working on: todo_api_app/README.md...
working on: ashwin_assignments/README.md...
working on: my_api_simple_app/README.md...
working on: user_without_nested_app/README.md...
working on: demo_api_fech_application/README.md...
working on: blog_post_comment/README.md...
working on: simple_userapp/README.md...


Dir.glob("**/*.txt") do |my_text_file| # note one extra "*"
irb(main):137:1*   puts "working on: #{my_text_file}..."
irb(main):138:0> end
working on: simple_userapp/node_modules/setimmediate/LICENSE.txt...
working on: simple_userapp/node_modules/regexpu-core/LICENSE-MIT.txt...
working on: simple_userapp/node_modules/regenerate-unicode-properties/LICENSE-MIT.txt...
working on: simple_userapp/node_modules/regjsgen/LICENSE-MIT.txt...
working on: simple_userapp/node_modules/unicode-match-property-ecmascript/LICENSE-MIT.txt...
working on: simple_userapp/node_modules/path-is-inside/LICENSE.txt...
working on: simple_userapp/node_modules/set-blocking/LICENSE.txt...
working on: simple_userapp/node_modules/chrome-trace-event/LICENSE.txt...
working on: simple_userapp/node_modules/punycode/LICENSE-MIT.txt...
working on: simple_userapp/node_modules/@webassemblyjs/leb128/LICENSE.txt...
working on: simple_userapp/node_modules/postcss-selector-parser/node_modules/cssesc/LICENSE-MIT.txt...
working on: simple_userapp/node_modules/unicode-match-property-value-ecmascript/LICENSE-MIT.txt...
working on: simple_userapp/node_modules/uri-js/node_modules/punycode/LICENSE-MIT.txt...
working on: simple_userapp/node_modules/mkdirp/bin/usage.txt...
working on: simple_userapp/node_modules/regjsparser/node_modules/jsesc/LICENSE-MIT.txt...
working on: simple_userapp/node_modules/unicode-canonical-property-names-ecmascript/LICENSE-MIT.txt...
working on: simple_userapp/node_modules/cliui/LICENSE.txt...
working on: simple_userapp/node_modules/unicode-property-aliases-ecmascript/LICENSE-MIT.txt...
working on: simple_userapp/node_modules/signal-exit/LICENSE.txt...
working on: simple_userapp/node_modules/jsesc/LICENSE-MIT.txt...
working on: simple_userapp/node_modules/emoji-regex/LICENSE-MIT.txt...
working on: simple_userapp/node_modules/cssesc/LICENSE-MIT.txt...
working on: simple_userapp/node_modules/node-libs-browser/node_modules/punycode/LICENSE-MIT.txt...
working on: simple_userapp/node_modules/yargs-parser/LICENSE.txt...
working on: simple_userapp/node_modules/require-main-filename/LICENSE.txt...
working on: simple_userapp/node_modules/stream-http/test/server/static/basic.txt...
working on: simple_userapp/node_modules/regenerate/LICENSE-MIT.txt...
working on: log.txt...


real 0.79
user 0.20
sys 0.06
