6. File generated from 5, copy it into new file(should be randomly generated with unique name) and create new file in which every character will be specified by (-)

File.open("d:output.txt", "r+") do |file|
irb(main):054:1*       arr = file.readlines
irb(main):055:1*       puts arr.inspect
irb(main):056:0> end

["\"this is my file handling work is The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... ch
he first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in 
() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...The canonical way to create a file object is by using the open() function. ... characters starting from the current reading position up to a newline character. ... The readline() method will return the first line, and then will point to the second line in the file. ... Use the 'rb' mode in the open() function to read a binary files, as shown ...\"\n"]


File.open("d:output.txt", "-") do |file|
irb(main):054:1*       arr = file.readlines
irb(main):055:1*       puts arr.inspect
irb(main):056:0> end


real 3.30
user 0.20
sys 0.12

